module.exports = [
  'Eazy-E',
  'Flavor Flav',
  'DJ Jazzy Jeff',
  'Coolio',
  'Beastie Boys',
  'Megashark',
  'Doge',
  'Slender Man',
  'Spongebob',
  'Ugandan Knuckles',
  'Scumbag Steve',
  'Good Guy Greg',
  'Bad Luck Brian',
  'Harambe',
  'Xzibit',
  'Pedobear',
  'Bear Grylls',
  'Mad Lad',
  'Goku',
  'Vegeta',
  'Woody Woodpecker',
  'Ron Burgundy',
  'Crocodile Dundee',
  'Freddie Mercury',
  'Hitler',
  'Marylin Monroe',
  'Albert Einstein',
  'Bill Gates',
  'Eric Cartman',
  'Austin Powers',
  'Rambo',
  'Snoop Dogg',
  'Barrack Obama',
  'Chuck Norris',
  'Elon Musk',
  'Technoviking',
  'Epic Beard Man',
  'Squidward',
  'Batman',
  'Zuckerberg',
  'Zoidberg',
  'Morpheus'
]
